apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "kubeseal-webgui.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "kubeseal-webgui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-api"
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: sealed-secrets-cert
            mountPath: /kubeseal-webgui/cert/kubeseal-cert.pem
            subPath: kubeseal-cert.pem
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /secrets
              port: http
          readinessProbe:
            httpGet:
              path: /secrets
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: "{{ .Chart.Name }}-ui"
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sealed-secrets-cert
          configMap:
            name: {{ include "kubeseal-webgui.fullname" . }}
