name: CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Contains application version'     
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            kubesealwebgui/test:${{ github.event.inputs.version }}
      - name: Build and push
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          push: true
          file: api/Dockerfile
          tags: |
            kubesealwebgui/api:latest
            kubesealwebgui/api:${{ github.event.inputs.version }}
      - name: Build and push
        id: docker_build_ui
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ui/Dockerfile
          tags: |
            kubesealwebgui/ui:latest
            kubesealwebgui/ui:${{ github.event.inputs.version }}
